// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnWThGAeQeuWayMcOD0an3Q-r0Qrrx5M',
    appId: '1:61394911218:web:2c828edffca18f71f6356b',
    messagingSenderId: '61394911218',
    projectId: 'flutter-auth-app-ca099',
    authDomain: 'flutter-auth-app-ca099.firebaseapp.com',
    storageBucket: 'flutter-auth-app-ca099.firebasestorage.app',
    measurementId: 'G-NNEHRR3Z29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cUvWngKeA3YwwkSAnu1EW6t69JhE27Y',
    appId: '1:61394911218:android:2eaecf9309040bacf6356b',
    messagingSenderId: '61394911218',
    projectId: 'flutter-auth-app-ca099',
    storageBucket: 'flutter-auth-app-ca099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanlRQ3Zbp67gLskm58CNMWt8UHHuwDFs',
    appId: '1:61394911218:ios:9b7c17139c558daff6356b',
    messagingSenderId: '61394911218',
    projectId: 'flutter-auth-app-ca099',
    storageBucket: 'flutter-auth-app-ca099.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanlRQ3Zbp67gLskm58CNMWt8UHHuwDFs',
    appId: '1:61394911218:ios:9b7c17139c558daff6356b',
    messagingSenderId: '61394911218',
    projectId: 'flutter-auth-app-ca099',
    storageBucket: 'flutter-auth-app-ca099.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsnWThGAeQeuWayMcOD0an3Q-r0Qrrx5M',
    appId: '1:61394911218:web:d3f1f368fe33c74cf6356b',
    messagingSenderId: '61394911218',
    projectId: 'flutter-auth-app-ca099',
    authDomain: 'flutter-auth-app-ca099.firebaseapp.com',
    storageBucket: 'flutter-auth-app-ca099.firebasestorage.app',
    measurementId: 'G-DWNS8F6EW2',
  );
}
